recipe_sha: a8520adadc6e0abc700caed83e2601f6fa1d3f9b14698f200038c746a58fde55  # The hash of the recipe's meta.yaml at which this recipe failed to build.
skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |2
     INFO (hhsuite,bin/ffindex_modify): Needed DSO aarch64-conda-linux-gnu/sysroot/lib64/ld-linux-aarch64.so.1 found in CDT/compiler package conda-forge/noarch::sysroot_linux-aarch64==2.17=h5b4a56d_14
     INFO (hhsuite,bin/hhblits_ca3m): Needed DSO lib/libstdc.so.6 found in conda-forge/linux-aarch64::libstdcxx-ng==13.2.0=h3f4de04_7
     INFO (hhsuite,bin/hhblits_ca3m): Needed DSO aarch64-conda-linux-gnu/sysroot/lib64/libm.so.6 found in CDT/compiler package conda-forge/noarch::sysroot_linux-aarch64==2.17=h5b4a56d_14
     INFO (hhsuite,bin/hhblits_ca3m): Needed DSO lib/libgomp.so.1 found in conda-forge/linux-aarch64::_openmp_mutex==4.5=2_gnu
     INFO (hhsuite,bin/hhblits_ca3m): Needed DSO lib/libgcc_s.so.1 found in conda-forge/linux-aarch64::libgcc-ng==13.2.0=he277a41_7
     INFO (hhsuite,bin/hhblits_ca3m): Needed DSO aarch64-conda-linux-gnu/sysroot/lib64/libpthread.so.0 found in CDT/compiler package conda-forge/noarch::sysroot_linux-aarch64==2.17=h5b4a56d_14
     INFO (hhsuite,bin/hhblits_ca3m): Needed DSO aarch64-conda-linux-gnu/sysroot/lib64/libc.so.6 found in CDT/compiler package conda-forge/noarch::sysroot_linux-aarch64==2.17=h5b4a56d_14
     INFO (hhsuite,bin/hhblits_ca3m): Needed DSO aarch64-conda-linux-gnu/sysroot/lib64/ld-linux-aarch64.so.1 found in CDT/compiler package conda-forge/noarch::sysroot_linux-aarch64==2.17=h5b4a56d_14
     INFO (hhsuite,bin/a3m_extract): Needed DSO lib/libstdc.so.6 found in conda-forge/linux-aarch64::libstdcxx-ng==13.2.0=h3f4de04_7
     INFO (hhsuite,bin/a3m_extract): Needed DSO lib/libgcc_s.so.1 found in conda-forge/linux-aarch64::libgcc-ng==13.2.0=he277a41_7
     INFO (hhsuite,bin/a3m_extract): Needed DSO aarch64-conda-linux-gnu/sysroot/lib64/libpthread.so.0 found in CDT/compiler package conda-forge/noarch::sysroot_linux-aarch64==2.17=h5b4a56d_14
     INFO (hhsuite,bin/a3m_extract): Needed DSO aarch64-conda-linux-gnu/sysroot/lib64/libc.so.6 found in CDT/compiler package conda-forge/noarch::sysroot_linux-aarch64==2.17=h5b4a56d_14
     INFO (hhsuite,bin/a3m_extract): Needed DSO aarch64-conda-linux-gnu/sysroot/lib64/ld-linux-aarch64.so.1 found in CDT/compiler package conda-forge/noarch::sysroot_linux-aarch64==2.17=h5b4a56d_14
     INFO (hhsuite,bin/hhblits): Needed DSO lib/libstdc.so.6 found in conda-forge/linux-aarch64::libstdcxx-ng==13.2.0=h3f4de04_7
     INFO (hhsuite,bin/hhblits): Needed DSO aarch64-conda-linux-gnu/sysroot/lib64/libm.so.6 found in CDT/compiler package conda-forge/noarch::sysroot_linux-aarch64==2.17=h5b4a56d_14
     INFO (hhsuite,bin/hhblits): Needed DSO lib/libgomp.so.1 found in conda-forge/linux-aarch64::_openmp_mutex==4.5=2_gnu
     INFO (hhsuite,bin/hhblits): Needed DSO lib/libgcc_s.so.1 found in conda-forge/linux-aarch64::libgcc-ng==13.2.0=he277a41_7
     INFO (hhsuite,bin/hhblits): Needed DSO aarch64-conda-linux-gnu/sysroot/lib64/libpthread.so.0 found in CDT/compiler package conda-forge/noarch::sysroot_linux-aarch64==2.17=h5b4a56d_14
     INFO (hhsuite,bin/hhblits): Needed DSO aarch64-conda-linux-gnu/sysroot/lib64/libc.so.6 found in CDT/compiler package conda-forge/noarch::sysroot_linux-aarch64==2.17=h5b4a56d_14
     INFO (hhsuite,bin/hhblits): Needed DSO aarch64-conda-linux-gnu/sysroot/lib64/ld-linux-aarch64.so.1 found in CDT/compiler package conda-forge/noarch::sysroot_linux-aarch64==2.17=h5b4a56d_14
  WARNING (hhsuite): interpreter (Python) package conda-forge/linux-aarch64::python==3.8.19=hbbe8eec_0_cpython in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to build/ignore_run_exports)
  WARNING (hhsuite): run-exports library package conda-forge/linux-aarch64::perl==5.32.1=7_h31becfc_perl5 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to build/ignore_run_exports)
  Fixing permissions
  Packaged license file/s.
  INFO :: Time taken to mark (prefix)
          0 replacements in 0 files was 0.05 seconds
  TEST START: /opt/conda/conda-bld/linux-aarch64/hhsuite-3.3.0-py38pl5321h7969c44_11.tar.bz2
  Renaming work directory '/opt/conda/conda-bld/hhsuite_1717777403189/work' to '/opt/conda/conda-bld/hhsuite_1717777403189/work_moved_hhsuite-3.3.0-py38pl5321h7969c44_11_linux-aarch64'
  shutil.move(work)=/opt/conda/conda-bld/hhsuite_1717777403189/work, dest=/opt/conda/conda-bld/hhsuite_1717777403189/work_moved_hhsuite-3.3.0-py38pl5321h7969c44_11_linux-aarch64)
  Reloading output folder (local): ...working... done
  Solving environment (_test_env): ...working... done

  ## Package Plan ##

    environment location: /opt/conda/conda-bld/hhsuite_1717777403189/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_


  The following NEW packages will be INSTALLED:

      _openmp_mutex:         4.5-2_gnu                   conda-forge
      bzip2:                 1.0.8-h31becfc_5            conda-forge
      ca-certificates:       2024.6.2-hcefe29a_0         conda-forge
      hhsuite:               3.3.0-py38pl5321h7969c44_11 local
      ld_impl_linux-aarch64: 2.40-h9fc2d93_2             conda-forge
      libffi:                3.4.2-h3557bc0_5            conda-forge
      libgcc-ng:             13.2.0-he277a41_7           conda-forge
      libgomp:               13.2.0-he277a41_7           conda-forge
      libnsl:                2.0.1-h31becfc_0            conda-forge
      libsqlite:             3.45.3-h194ca79_0           conda-forge
      libstdcxx-ng:          13.2.0-h3f4de04_7           conda-forge
      libuuid:               2.38.1-hb4cce97_0           conda-forge
      libxcrypt:             4.4.36-h31becfc_1           conda-forge
      libzlib:               1.3.1-h68df207_1            conda-forge
      ncurses:               6.5-h0425590_0              conda-forge
      openssl:               3.3.1-h68df207_0            conda-forge
      perl:                  5.32.1-7_h31becfc_perl5     conda-forge
      pip:                   24.0-pyhd8ed1ab_0           conda-forge
      python:                3.8.19-hbbe8eec_0_cpython   conda-forge
      python_abi:            3.8-4_cp38                  conda-forge
      readline:              8.2-h8fc344f_1              conda-forge
      setuptools:            70.0.0-pyhd8ed1ab_0         conda-forge
      tk:                    8.6.13-h194ca79_0           conda-forge
      wheel:                 0.43.0-pyhd8ed1ab_1         conda-forge
      xz:                    5.2.6-h9cdd2b7_0            conda-forge

  DEBUG:urllib3.util.retry:Incremented Retry for (url='/conda-forge/linux-aarch64/python_abi-3.8-4_cp38.conda'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
  WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xff4f83093640>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /conda-forge/linux-aarch64/python_abi-3.8-4_cp38.conda
  DEBUG:urllib3.util.retry:Incremented Retry for (url='/conda-forge/linux-aarch64/python_abi-3.8-4_cp38.conda'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
  WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xff4f83093310>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /conda-forge/linux-aarch64/python_abi-3.8-4_cp38.conda
  DEBUG:urllib3.util.retry:Incremented Retry for (url='/conda-forge/linux-aarch64/python_abi-3.8-4_cp38.conda'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
  WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xff4f3d89a080>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /conda-forge/linux-aarch64/python_abi-3.8-4_cp38.conda
  Traceback (most recent call last):
    File "/opt/conda/bin/conda-build", line 11, in <module>
      sys.exit(execute())
    File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 590, in execute
      api.build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 250, in build
      return build_tree(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3653, in build_tree
      test(pkg, config=metadata.config.copy(), stats=stats)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3397, in test
      environ.create_env(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 1049, in create_env
      _execute_actions(prefix, precs)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 1332, in _execute_actions
      progressive_fetch_extract.execute()
    File "/opt/conda/lib/python3.10/site-packages/conda/core/package_cache_data.py", line 891, in execute
      raise CondaMultiError(not_cancelled)
  conda.CondaMultiError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/linux-aarch64/python_abi-3.8-4_cp38.conda>
  Elapsed: -

  An HTTP error occurred when trying to retrieve this URL.
  HTTP errors are often intermittent, and a simple retry will get you on your way.

  HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/linux-aarch64/python_abi-3.8-4_cp38.conda>
  Elapsed: -

  An HTTP error occurred when trying to retrieve this URL.
  HTTP errors are often intermittent, and a simple retry will get you on your way.
# Last 100 lines of the build log.
