recipe_sha: af7c501705200feca169c8deaa0e4af65a23addfb02686d915c79a07e2787b0b  # The hash of the recipe's meta.yaml at which this recipe failed to build.
skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |2
      binutils_linux-64:        2.40-hdade7a5_3         conda-forge
      bzip2:                    1.0.8-hd590300_5        conda-forge
      c-ares:                   1.28.1-hd590300_0       conda-forge
      ca-certificates:          2024.6.2-hbcca054_0     conda-forge
      cmake:                    3.29.4-h91dbaaa_0       conda-forge
      gcc_impl_linux-64:        12.3.0-h58ffeeb_7       conda-forge
      gcc_linux-64:             12.3.0-h6477408_3       conda-forge
      gxx_impl_linux-64:        12.3.0-h2a574ab_7       conda-forge
      gxx_linux-64:             12.3.0-h4a1b8e8_3       conda-forge
      kernel-headers_linux-64:  2.6.32-he073ed8_17      conda-forge
      keyutils:                 1.6.1-h166bdaf_0        conda-forge
      krb5:                     1.21.2-h659d440_0       conda-forge
      ld_impl_linux-64:         2.40-hf3520f5_1         conda-forge
      libcurl:                  8.8.0-hca28451_0        conda-forge
      libedit:                  3.1.20191231-he28a2e2_2 conda-forge
      libev:                    4.33-hd590300_2         conda-forge
      libexpat:                 2.6.2-h59595ed_0        conda-forge
      libgcc-devel_linux-64:    12.3.0-h0223996_107     conda-forge
      libgcc-ng:                13.2.0-h77fa898_7       conda-forge
      libgomp:                  13.2.0-h77fa898_7       conda-forge
      libnghttp2:               1.58.0-h47da74e_1       conda-forge
      libsanitizer:             12.3.0-hb8811af_7       conda-forge
      libssh2:                  1.11.0-h0841786_0       conda-forge
      libstdcxx-devel_linux-64: 12.3.0-h0223996_107     conda-forge
      libstdcxx-ng:             13.2.0-hc0a3c3a_7       conda-forge
      libuv:                    1.48.0-hd590300_0       conda-forge
      libzlib:                  1.3.1-h4ab18f5_1        conda-forge
      make:                     4.3-hd18ef5c_1          conda-forge
      ncurses:                  6.5-h59595ed_0          conda-forge
      openssl:                  3.3.0-h4ab18f5_3        conda-forge
      rhash:                    1.4.4-hd590300_0        conda-forge
      sysroot_linux-64:         2.12-he073ed8_17        conda-forge
      xz:                       5.2.6-h166bdaf_0        conda-forge
      zstd:                     1.5.6-ha6fb4c9_0        conda-forge

  Preparing transaction: ...working... done
  Verifying transaction: ...working... failed
  Traceback (most recent call last):
    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 1049, in create_env
      _execute_actions(prefix, precs)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 1334, in _execute_actions
      unlink_link_transaction.execute()
    File "/opt/conda/lib/python3.10/site-packages/conda/core/link.py", line 348, in execute
      self.verify()
    File "/opt/conda/lib/python3.10/site-packages/conda/common/io.py", line 86, in decorated
      return f(*args, **kwds)
    File "/opt/conda/lib/python3.10/site-packages/conda/core/link.py", line 304, in verify
      exceptions = self._verify(self.prefix_setups, self.prefix_action_groups)
    File "/opt/conda/lib/python3.10/site-packages/conda/core/link.py", line 810, in _verify
      for exc in self.verify_executor.map(
    File "/opt/conda/lib/python3.10/site-packages/conda/common/io.py", line 571, in map
      yield func(thing)
    File "/opt/conda/lib/python3.10/site-packages/conda/core/link.py", line 587, in _verify_individual_level
      error_result = axn.verify()
    File "/opt/conda/lib/python3.10/site-packages/conda/core/path_actions.py", line 514, in verify
      create_link(self.source_full_path, self.intermediate_path, LinkType.copy)
    File "/opt/conda/lib/python3.10/site-packages/conda/gateways/disk/create.py", line 397, in create_link
      copy(src, dst)
    File "/opt/conda/lib/python3.10/site-packages/conda/gateways/disk/create.py", line 327, in copy
      _do_copy(src, dst)
    File "/opt/conda/lib/python3.10/site-packages/conda/gateways/disk/create.py", line 341, in _do_copy
      copyfileobj(fsrc, fdst, buffer_size)
    File "/opt/conda/lib/python3.10/shutil.py", line 198, in copyfileobj
      fdst_write(buf)
  OSError: [Errno 28] No space left on device

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/opt/conda/bin/conda-build", line 11, in <module>
      sys.exit(execute())
    File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 590, in execute
      api.build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 250, in build
      return build_tree(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3638, in build_tree
      packages_from_this = build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2409, in build
      create_build_envs(top_level_pkg, notest)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2253, in create_build_envs
      environ.create_env(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 1177, in create_env
      create_env(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 1049, in create_env
      _execute_actions(prefix, precs)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 1334, in _execute_actions
      unlink_link_transaction.execute()
    File "/opt/conda/lib/python3.10/site-packages/conda/core/link.py", line 348, in execute
      self.verify()
    File "/opt/conda/lib/python3.10/site-packages/conda/common/io.py", line 86, in decorated
      return f(*args, **kwds)
    File "/opt/conda/lib/python3.10/site-packages/conda/core/link.py", line 307, in verify
      maybe_raise(CondaMultiError(exceptions), context)
    File "/opt/conda/lib/python3.10/site-packages/conda/exceptions.py", line 1222, in maybe_raise
      raise error
  conda.CondaMultiError: The current user does not have write permissions to the target environment.
    environment location: /opt/conda/conda-bld/lrez_1717513766120/_build_env
    uid: 1001
    gid: 1001
# Last 100 lines of the build log.
