recipe_sha: acd4df42912f5dcaa4d69af641fe5ff261084b2dc0df6783426b144aad34de10  # The hash of the recipe's meta.yaml at which this recipe failed to build.
skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |2-
      libnsl:           2.0.1-hd590300_0          conda-forge
      libsqlite:        3.45.3-h2797004_0         conda-forge
      libuuid:          2.38.1-h0b41bf4_0         conda-forge
      libxcrypt:        4.4.36-hd590300_1         conda-forge
      libzlib:          1.3.1-h4ab18f5_1          conda-forge
      ncurses:          6.5-h59595ed_0            conda-forge
      openssl:          3.3.1-h4ab18f5_0          conda-forge
      packaging:        24.0-pyhd8ed1ab_0         conda-forge
      pip:              24.0-pyhd8ed1ab_0         conda-forge
      pluggy:           1.5.0-pyhd8ed1ab_0        conda-forge
      pytest:           8.2.2-pyhd8ed1ab_0        conda-forge
      pytest-runner:    6.0.0-pyhd8ed1ab_0        conda-forge
      python:           3.12.3-hab00c5b_0_cpython conda-forge
      readline:         8.2-h8228510_1            conda-forge
      setuptools:       70.0.0-pyhd8ed1ab_0       conda-forge
      tk:               8.6.13-noxft_h4845f30_101 conda-forge
      tomli:            2.0.1-pyhd8ed1ab_0        conda-forge
      tzdata:           2024a-h0c530f3_0          conda-forge
      wheel:            0.43.0-pyhd8ed1ab_1       conda-forge
      xz:               5.2.6-h166bdaf_0          conda-forge

  Preparing transaction: ...working... done
  Verifying transaction: ...working... done
  Executing transaction: ...working... done
  Reloading output folder (file:///opt/host-conda-bld): ...working... done
  Solving environment (_test_env): ...working... done
  Source cache directory is: /opt/conda/conda-bld/src_cache
  Downloading source to cache: profile_dists-1.0.1_440622e653.tar.gz
  Downloading https://pypi.io/packages/source/p/profile_dists/profile_dists-1.0.1.tar.gz
  Success
  Extracting download
  source tree in: /opt/conda/conda-bld/profile_dists_1717794474238/work
  export PREFIX=/opt/conda/conda-bld/profile_dists_1717794474238/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold
  export BUILD_PREFIX=/opt/conda/conda-bld/profile_dists_1717794474238/_build_env
  export SRC_DIR=/opt/conda/conda-bld/profile_dists_1717794474238/work
  Using pip 24.0 from $PREFIX/lib/python3.12/site-packages/pip (python 3.12)
  Non-user install because user site-packages disabled
  Ignoring indexes: https://pypi.org/simple
  Created temporary directory: /tmp/pip-build-tracker-2b6bll2j
  Initialized build tracking at /tmp/pip-build-tracker-2b6bll2j
  Created build tracker: /tmp/pip-build-tracker-2b6bll2j
  Entered build tracker: /tmp/pip-build-tracker-2b6bll2j
  Created temporary directory: /tmp/pip-install-a8yv71x9
  Created temporary directory: /tmp/pip-ephem-wheel-cache-9ch263r9
  Processing $SRC_DIR
    Added file://$SRC_DIR to build tracker '/tmp/pip-build-tracker-2b6bll2j'
    Created temporary directory: /tmp/pip-modern-metadata-7jwml2pb
    Preparing metadata (pyproject.toml): started
    Running command Preparing metadata (pyproject.toml)
    Preparing metadata (pyproject.toml): finished with status 'done'
    Source in $SRC_DIR has version 1.0.1, which satisfies requirement profile_dists==1.0.1 from file://$SRC_DIR
    Removed profile_dists==1.0.1 from file://$SRC_DIR from build tracker '/tmp/pip-build-tracker-2b6bll2j'
  INFO: pip is looking at multiple versions of profile-dists to determine which version is compatible with other requirements. This could take a while.
  Will try a different candidate, due to conflict:
      profile-dists 1.0.1 depends on Python <3.12,>=3.8.2
  [31mERROR: Package 'profile-dists' requires a different Python: 3.12.3 not in '<3.12,>=3.8.2'[0m[31m
  [0mException information:
  Traceback (most recent call last):
    File "$PREFIX/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
      result = self._result = resolver.resolve(
                              ^^^^^^^^^^^^^^^^^
    File "$PREFIX/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
      state = resolution.resolve(requirements, max_rounds=max_rounds)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "$PREFIX/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 439, in resolve
      raise ResolutionImpossible(self.state.backtrack_causes)
  pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=RequiresPythonRequirement('<3.12,>=3.8.2'), parent=LinkCandidate('file://$SRC_DIR'))]

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "$PREFIX/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
      status = run_func(*args)
               ^^^^^^^^^^^^^^^
    File "$PREFIX/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
      return func(self, options, args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "$PREFIX/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 377, in run
      requirement_set = resolver.resolve(
                        ^^^^^^^^^^^^^^^^^
    File "$PREFIX/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 104, in resolve
      raise error from e
  pip._internal.exceptions.UnsupportedPythonVersion: Package 'profile-dists' requires a different Python: 3.12.3 not in '<3.12,>=3.8.2'
  Removed build tracker: '/tmp/pip-build-tracker-2b6bll2j'
  Traceback (most recent call last):
    File "/opt/conda/bin/conda-build", line 11, in <module>
      sys.exit(execute())
    File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 590, in execute
      api.build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 250, in build
      return build_tree(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3638, in build_tree
      packages_from_this = build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2506, in build
      utils.check_call_env(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 405, in check_call_env
      return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 381, in _func_defaulting_env_to_os_environ
      raise subprocess.CalledProcessError(proc.returncode, _args)
  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/profile_dists_1717794474238/work/conda_build.sh']' returned non-zero exit status 1.
# Last 100 lines of the build log.
